using static DxLibDLL.DX;

namespace DXCalculator;

/// <summary>
/// KeyCode
/// </summary>
public enum KeyCode
{
    BackSpace = KEY_INPUT_BACK,
    Tab = KEY_INPUT_TAB,
    Enter = KEY_INPUT_RETURN,
    LeftShift = KEY_INPUT_LSHIFT,
    RightShift = KEY_INPUT_RSHIFT,
    LeftControl = KEY_INPUT_LCONTROL,
    RightControl = KEY_INPUT_RCONTROL,
    Escape = KEY_INPUT_ESCAPE,
    Space = KEY_INPUT_SPACE,
    PageUp = KEY_INPUT_PGUP,
    PageDown = KEY_INPUT_PGDN,
    End = KEY_INPUT_END,
    Home = KEY_INPUT_HOME,
    Left = KEY_INPUT_LEFT,
    Right = KEY_INPUT_RIGHT,
    Up = KEY_INPUT_UP,
    Down = KEY_INPUT_DOWN,
    Insert = KEY_INPUT_INSERT,
    Delete = KEY_INPUT_DELETE,
    Minum = KEY_INPUT_MINUS,
    Yen = KEY_INPUT_YEN,
    Prevtracl = KEY_INPUT_PREVTRACK,
    Period = KEY_INPUT_PERIOD,
    Slash = KEY_INPUT_SLASH,
    LeftAlt = KEY_INPUT_LALT,
    RightAlt = KEY_INPUT_RALT,
    ScrollLock = KEY_INPUT_SCROLL,
    Semicolon = KEY_INPUT_SEMICOLON,
    Colon = KEY_INPUT_COLON,
    LbRacket = KEY_INPUT_LBRACKET,
    RbRacket = KEY_INPUT_RBRACKET,
    At = KEY_INPUT_AT,
    CapsLock = KEY_INPUT_CAPSLOCK,
    PauseBreak = KEY_INPUT_PAUSE,

    Num0 = KEY_INPUT_NUMPAD0,
    Num1 = KEY_INPUT_NUMPAD1,
    Num2 = KEY_INPUT_NUMPAD2,
    Num3 = KEY_INPUT_NUMPAD3,
    Num4 = KEY_INPUT_NUMPAD4,
    Num5 = KEY_INPUT_NUMPAD5,
    Num6 = KEY_INPUT_NUMPAD6,
    Num7 = KEY_INPUT_NUMPAD7,
    Num8 = KEY_INPUT_NUMPAD8,
    Num9 = KEY_INPUT_NUMPAD9,
    Multiply = KEY_INPUT_MULTIPLY,
    Add = KEY_INPUT_ADD,
    Subtrack = KEY_INPUT_SUBTRACT,
    Decimal = KEY_INPUT_DECIMAL,
    Divide = KEY_INPUT_DIVIDE,
    NumPadEnter = KEY_INPUT_NUMPADENTER,

    F1 = KEY_INPUT_F1,
    F2 = KEY_INPUT_F2,
    F3 = KEY_INPUT_F3,
    F4 = KEY_INPUT_F4,
    F5 = KEY_INPUT_F5,
    F6 = KEY_INPUT_F6,
    F7 = KEY_INPUT_F7,
    F8 = KEY_INPUT_F8,
    F9 = KEY_INPUT_F9,
    F10 = KEY_INPUT_F10,
    F11 = KEY_INPUT_F11,
    F12 = KEY_INPUT_F12,

    A = KEY_INPUT_A,
    B = KEY_INPUT_B,
    C = KEY_INPUT_C,
    D = KEY_INPUT_D,
    E = KEY_INPUT_E,
    F = KEY_INPUT_F,
    G = KEY_INPUT_G,
    H = KEY_INPUT_H,
    I = KEY_INPUT_I,
    J = KEY_INPUT_J,
    K = KEY_INPUT_K,
    L = KEY_INPUT_L,
    M = KEY_INPUT_M,
    N = KEY_INPUT_N,
    O = KEY_INPUT_O,
    P = KEY_INPUT_P,
    Q = KEY_INPUT_Q,
    R = KEY_INPUT_R,
    S = KEY_INPUT_S,
    T = KEY_INPUT_T,
    U = KEY_INPUT_U,
    V = KEY_INPUT_V,
    W = KEY_INPUT_W,
    X = KEY_INPUT_X,
    Y = KEY_INPUT_Y,
    Z = KEY_INPUT_Z
}